# Generated by Django 3.2.12 on 2022-02-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220211_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='name',
        ),
    ]
