# Generated by Django 3.2.12 on 2022-02-16 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_answer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
