# Generated by Django 3.2.12 on 2022-04-29 10:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_answer_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
