# Generated by Django 3.2.12 on 2022-04-29 11:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
