# Generated by Django 3.2.12 on 2022-04-30 09:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_question_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='another_image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='another_image_description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='other_image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='other_image_description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='remark',
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
