# Generated by Django 3.2.12 on 2022-05-01 09:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220430_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
