# Generated by Django 3.2.12 on 2022-05-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_answer_answer_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='content',
            new_name='answer',
        ),
    ]
